# -*- coding: utf-8 -*-
"""StreamlitApp.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q701-Tb8BlXijAkrJaQLLiGgliOivXyM
"""
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Generate synthetic data
np.random.seed(42)
num_players = 1000
levels = 10

data = {
    'player_id': np.arange(1, num_players + 1),
    'level_achieved': np.random.randint(1, levels + 1, num_players),
    'level_cleared': np.random.randint(1, levels + 1, num_players),
    'attempts': np.random.randint(1, 11, num_players),
    'difficulty': np.random.randint(1, 7, num_players),
}

df = pd.DataFrame(data)

# Train a model to predict next level and difficulty based on attempts, level achieved, and level cleared
X = df[['attempts', 'level_achieved', 'level_cleared']]
y_level = df['level_achieved'] + 1  # Next level prediction
y_difficulty = df['difficulty'] + 1  # Next difficulty prediction

level_model = LinearRegression()
difficulty_model = LinearRegression()

level_model.fit(X, y_level)
difficulty_model.fit(X, y_difficulty)

# Streamlit UI
st.title("Game Player Analytics & Next Level Prediction")

# User input for prediction
st.header("Predict Next Level and Difficulty")
user_attempts = st.number_input("Enter Number of Attempts", min_value=1, max_value=10, value=5)
user_level_achieved = st.number_input("Enter Level Achieved", min_value=1, max_value=10, value=5)
user_level_cleared = st.number_input("Enter Level Cleared", min_value=1, max_value=10, value=5)

if st.button("Predict Next Level & Difficulty"):
    next_level = level_model.predict([[user_attempts, user_level_achieved, user_level_cleared]])
    next_difficulty = difficulty_model.predict([[user_attempts, user_level_achieved, user_level_cleared]])
    
    st.write(f"Predicted Next Level: {int(next_level[0])}")
    st.write(f"Predicted Next Difficulty: {int(next_difficulty[0])}")

